name: Flutter CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./focus_tree

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Verify formatting
        run: flutter format --set-exit-if-changed .
        
      - name: Analyze project source
        run: flutter analyze
        
      - name: Run tests
        run: flutter test

  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./focus_tree
    needs: build
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: focus_tree/build/app/outputs/flutter-apk/app-debug.apk 